INSERT INTO token
(name, symbol)
values
('EOS', 'EOS'),
('OmiseGO', 'OMG'),
('Populous', 'PPT'),
('Augur', 'REP'),
('QASH', 'QASH'),
('SALT', 'SALT'),
('Veritaseum', 'VERI'),
('Golem', 'GNT'),
('TenX', 'PAY'),
('Binance Coin', 'BNB'),
('Status', 'SNT'),
('Power Ledger', 'POWR'),
('Walton', 'WTC'),
('DigixDAO', 'DGD'),
('Basic Attention Token', 'BAT'),
('Kyber Network', 'KNC'),
('Santiment Network Token', 'SAN'),
('Exchange Union', 'XUC'),
('Raiden Network Token', 'RDN'),
('Iconomi', 'ICN'),
('Gnosis', 'GNO'),
('TRON', 'TRX'),
('Monaco', 'MCO'),
('Aeternity', 'AE'),
('Civic', 'CVC'),
('Metal', 'MTL'),
('FunFair', 'FUN'),
('Bytom', 'BTM'),
('Bancor', 'BNT'),
('Ethos', 'ETHOS'),
('0x', 'ZRX'),
('Storj', 'STORJ'),
('ChainLink', 'LINK'),
('Edgeless', 'EDG'),
('SingularDTV', 'SNGLS'),
('Substratum', 'SUB'),
('AdEx', 'ADX'),
('RChain', 'RHOC'),
('Loopring', 'LRC'),
('Quantstamp', 'QSP'),
('Aragon', 'ANT'),
('Ripio Credit Network', 'RCN'),
('Streamr DATAcoin', 'DATA'),
('MobileGo', 'MGO'),
('Quantum Resistant Ledger', 'QRL'),
('Request Network', 'REQ'),
('iExec RLC', 'RLC'),
('Wings', 'WINGS'),
('Revain', 'R'),
('ATMChain', 'ATM'),
('SONM', 'SNM'),
('Cobinhood', 'COB'),
('Kin', 'KIN'),
('PayPie', 'PPP'),
('Open Trading Network', 'OTN'),
('bitqy', 'BQ'),
('MCAP', 'MCAP'),
('Decentraland', 'MANA'),
('Enigma', 'ENG'),
('WeTrust', 'TRST'),
('Cofound.it', 'CFI'),
('Melon', 'MLN'),
('AirSwap', 'AST'),
('Time New Bank', 'TNB'),
('Tierion', 'TNT'),
('FirstBlood', '1ST'),
('CoinDash', 'CDT'),
('Pillar', 'PLR'),
('Zeusshield', 'ZSC'),
('Modum', 'MOD'),
('Blocktix', 'TIX'),
('TaaS', 'TAAS'),
('Grid+', 'GRID'),
('Numeraire', 'NMR'),
('district0x', 'DNT'),
('Centra', 'CTR'),
('Ambrosus', 'AMB'),
('Cindicator', 'CND'),
('Matchpool', 'GUP'),
('Xaurum', 'XAUR'),
('Paypex', 'PAYX'),
('Eidoo', 'EDO'),
('Moeda Loyalty Points', 'MDA'),
('Viberate', 'VIB'),
('Humaniq', 'HMQ'),
('Genesis Vision', 'GVT')
